language: python
install:
- pip install mkdocs
script:
- git clean -f -d -x
after_success:
- git remote add build "https://${GH_TOKEN}@github.com/drupalcorn/guide.git";
- git fetch build && git fetch all
- mkdocs gh-deploy -v --clean --remote-name build;
