site_name: DrupalCorn Guide
theme: readthedocs
repo_url: https://github.com/drupalcorn/guide
nav:
  - About:
    - About this Guide: 'index.md'
    - Structure: 'structure.md'
    - History: 'history.md'
  - Identity and Branding: 'identity/index.md'
  - Camp Planning:
    - Timeline: 'camp-planning/timeline.md'
    - Meetings: 'camp-planning/meetings.md'
    - Venue and Dates: 'camp-planning/venue_dates.md'
    - Website: 'camp-planning/website.md'
    - Sponsors: 'camp-planning/sponsors.md'
    - Lodging: 'camp-planning/lodging.md'
    - Marketing: 'camp-planning/marketing.md'
    - Sessions: 'camp-planning/sessions.md'
    - Volunteers: 'camp-planning/volunteers.md'
    - Video Capture: 'camp-planning/video.md'
    - Registration: 'camp-planning/registration.md'
    - Catering: 'camp-planning/catering.md'
    - Friends of DrupalCorn Dinner: 'camp-planning/friends_dinner.md'
    - Party: 'camp-planning/party.md'
    - Training Day: 'camp-planning/training_day.md'
    - Session Days: 'camp-planning/session_days.md'
    - Sprint / Contribution Day: 'camp-planning/contrib_day.md'
    - Post-Camp Analysis: 'camp-planning/post_camp.md'
  - Code of Conduct:
    - Code of Conduct: 'code-of-conduct.md'
    - Managing Complaints: 'complaints.md'
markdown_extensions:
    - toc:
        permalink: "#"
        
